### PR TITLE
JSON: fix 0/1 integer parsing

### LINKED ISSUE #781: JSON: incorrectly handles some values
Similar to #775, the JSON parser incorrectly parses some values. This JSON file:
```json
{
  "count": 3,
  "feature": true,
  "other": false,
  "zero": 0
}
```

Becomes:
```swift
internal enum JSONFiles {
  internal static let count: Int = 5
  internal static let feature: Bool = 1
  internal static let other: Bool = 0
  internal static let zero: Bool = 0
}
```

So, what's wrong here is:
- The value of the 2 booleans is incorrectly generated
- The type of the `zero` property is `Bool` instead of `Int`. From more testing it incorrectly parses 0 and 1 integers, and arrays that could be confused as one type or the other. All because of NSNumber shenanigans.

PR #783 fixes the first issue. The second one seems to be an issue with `JSONSerialization`.

---------

Applying the `AnyCodable` fix from #779 generates this Swift code:
```swift
internal enum JSONFiles {
  internal static let count: Date = 5
  internal static let feature: Bool = true
  internal static let other: Bool = false
  internal static let zero: Date = 2001-01-01 00:00:00 +0000
}
```

Clearly the `Date` check is a bit too eager here. Temporarily removing `Date` parsing gives:
```swift
internal enum JSONFiles {
  internal static let count: Int = 5
  internal static let feature: Bool = true
  internal static let other: Bool = false
  internal static let zero: Int = 0
}
```

So couple of things to note:
- Need a variant of `AnyCodable` without `Date` parsing. Maybe subclassing `AnyCodable` with `AnyCodableIncludingDate`?
- The performance is really bad... For a 3.5MB file, `JSONSerialization` takes 0.028s, whereas `AnyCodable` takes 2.551s, about **91 times slower**.
- Maybe a JSON parser option to switch between `AnyCodable` and `JSONSerialization` parsers? The default should be `AnyCodable` (slower but more correct), and it's up to the end-user to write templates that handle bizarre/broken data?

### PR DESCRIPTION
**Pull request by djbe**
Fixes #781 

With JSONSerialization, 0 and 1 are parsed as `NSNumber`s. The issue is that these values are considered valid boolean values, so the `is Bool` or `is [Bool]` tests succeed.

This PR addresses the issue using runtime introspection.

## Implementation

There is no "simple" check to see what's actually inside an `NSNumber` instance. We first have to check if it's a boolean, and if not, get the internal type of the number. We then map these to the info we actually want.

The fix for `Array`s is a bit more involved, because `[NSNumber]` is tool free bridged to `[Int]`, `[Bool]`, etc... And the same applies to the inverse (a `[Bool]` is bridged to `[NSNumber]`). When we just check if something is `[NSNumber]` (and sometimes bridge it), we lose the easy check to see if all the elements in an array have the same type. We'd have to go through each element and check their type.

Without this extra array inspection (see commit b12aaa3da413d68d4b397a70f142afacd1d68806), things break. In the old method, `[0.1, 2, true]` is considered a `[Double]` array (see `mixed2` in the tests). This generates wrong Swift code, which causes compilation to fail:
```swift
static let mixed2: [Double] = [0.1, 2, true]
```

## Note

This issue **does not** appear in the YAML or Plist parsers. I've added a bunch of tests for all 3 parsers to verify some scenarios.

### CODE REVIEW

**Comment by SwiftGen-Eve** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Big PR</td>
    </tr>
  </tbody>
</table>

Hey 👋 I'm Eve, the friendly bot watching over SwiftGen 🤖

Thanks a lot for your contribution!



---

Seems like everything is in order 👍 You did a good job here! 🤝

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by AliSoftware** [comment]
What about using Codable (and our AnyCodable helper recently introduced to fix a similar issue in Plist) instead?

**Comment by djbe** [comment]
@AliSoftware see #781 where I did some tests with AnyCodable, the performance isn't that good unfortunately.

File: Sources/SwiftGenKit/Utils/Metadata.swift [hunk 1]
```diff
@@ -36,32 +36,35 @@ enum Metadata {
   /// - Parameter data: The value to describe
   /// - Returns: Dictionary with type information about the value (for Stencil context)
   static func generate(for data: Any) -> [String: Any] {
-    switch data {
-    case is String:
+    let dataType = type(of: data)
+
+    if data is String {
```
Comment (AliSoftware) [inline Sources/SwiftGenKit/Utils/Metadata.swift:44]: I think it could be worth a code comment to explain (iiuc) that this code uses `data is X` when we want toll-free-bridging to apply but `dataType == X.self` when we want to avoid TFB like for Int/Bool/… which could be misinterpreted and mis-bridged when coming in as NSNumber.

**Review by AliSoftware — APPROVED** [review]
I feel like we're adding more and more special cases as we encounter differences between JSONSerialization/Codable/YAMS interpreting things differently each; that also doesn't inspire confidence regarding unit tests (which always go through the intermediate state of YAML representation while real run doesn't)…

I really wish we could find a satisfying unified solution for those behavior diffs between test vs run one day…


Apart from that, the fix looks ok to me and should do (until we hopefully solve the bigger problem one day?)

**Comment by djbe** [comment]
There are actually quite a few things going here (and all the other issues):
- Wild world of unstructured input data, anything goes (unfortunately?)
- Using `JSONSerialization` for performance reasons, which uses ObjC types internally
- Our metadata runtime inspection
- Swift implicit toll-free bridging, which we can't turn off even if we wanted to (for some cases)

I can always check if there are other (faster) JSON parsers directly to Swift types, although I'm not 100% sure it will fix everything. I think the other parsers are working correctly, it's only `JSONSerialization` + ObjC types that are throwing a wrench in things.

Note: let's also not forget that `Stencil` sometimes does weird things too, especially when outputting/writing the content of a variable.

**Comment by AliSoftware** [comment]
Yeah which is why even if I think the ideal solution would be to find a _fast_ parser that would parse directly into _Swift_ types, I'm not sure such parser combining the two (Swift types + top performance) would be easy to find. So for now keeping NSJSONserialization + having those fixes to handle those "wild world of unstructured data" indeed, should be enough 👍
