### PR TITLE
Colors: fix `publicAccess` modifiers

### LINKED ISSUE #548: Colors: `publicAccess` parameter does not make internal code public
I'm working with SwiftGen's "color" generation. I noticed when using the `literals-swift4` template, and passing `publicAccess: true` in the parameters, it only made the main enum public, not the values inside it. Is this expected behavior? It was unexpected to me, but I understand there may be a good reason for it that I don't know about.

Here's what the generated code looks like:

```swift
public extension ColorName {
  enum HIGColors {
    /// 0x007affff (r: 0, g: 122, b: 255, a: 255)
    static let blue = #colorLiteral(red: 0.0, green: 0.47843137, blue: 1.0, alpha: 1.0)
    /// 0x4cd964ff (r: 76, g: 217, b: 100, a: 255)
    static let green = #colorLiteral(red: 0.29803923, green: 0.8509804, blue: 0.39215687, alpha: 1.0)
  }
  enum Q3Colors {
    /// 0x5b73aaff (r: 91, g: 115, b: 170, a: 255)
    static let blue = #colorLiteral(red: 0.35686275, green: 0.4509804, blue: 0.6666667, alpha: 1.0)
    /// 0xaa925bff (r: 170, g: 146, b: 91, a: 255)
    static let gold = #colorLiteral(red: 0.6666667, green: 0.57254905, blue: 0.35686275, alpha: 1.0)
  }
}
```

In my case, I'm generating this inside of a library, and then using the library within an app. My issue is, I'm not able to access the colors within the `HIGColors` and `Q3Colors` enums.

The code below gives me an error that says, `'blue' is inaccessible due to 'internal' protection level`

```swift
let blueColor = ColorName.HIGColors.blue
```

This can be fixed by adding `public` to the internal `enum` values, and their properties, like so:

```swift
public extension ColorName {
  public enum HIGColors {
    /// 0x007affff (r: 0, g: 122, b: 255, a: 255)
    public static let blue = #colorLiteral(red: 0.0, green: 0.47843137, blue: 1.0, alpha: 1.0)
    /// 0x4cd964ff (r: 76, g: 217, b: 100, a: 255)
    public static let green = #colorLiteral(red: 0.29803923, green: 0.8509804, blue: 0.39215687, alpha: 1.0)
// ...
```

## Environment
- SwiftGen Version: SwiftGen v6.0.2 (Stencil v0.13.1, StencilSwiftKit v2.7.1, SwiftGenKit v6.0.2)
- Xcode Version: 10.0

### PR DESCRIPTION
**Pull request by hisaac**
* [x] I've started my branch from the `develop` branch (gitflow)
* [x] I've added an entry in the `CHANGELOG.md` file to explain my changes and credit myself  
      _(or added `#trivial` to the PR title if I think it doesn't warrant a mention in the CHANGELOG)_
  * [x] Add the entry in the appropriate section (Bug Fix / New Feature / Breaking Change / Internal Change)
  * [x] Add a period and 2 spaces at the end of your short entry description
  * [x] Add links to your GitHub profile to credit yourself and to the related PR and issue after your description

---

Fixes #548.

This PR fixes two issues:

1. The `public` access modifier was not being added correctly when using `publicAccess: true` on the `literals-swift3` and `literals-swift4` templates.
2. Removed superfluous access modifiers from the `swift3` and `swift4` templates (based off of a comment from @djbe here: https://github.com/SwiftGen/SwiftGen/issues/548#issuecomment-427953553).

This includes updates to the stencil template files to correct the issues, and updates to the test data to match the changes.

All tests are currently passing.

### CODE REVIEW

**Comment by SwiftGen-Eve** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Feature branches should start from and be merged into ‘develop’, not master</td>
    </tr>
  </tbody>
</table>

Hey 👋 I'm Eve, the friendly bot watching over SwiftGen 🤖

Thanks a lot for your contribution!



---

Once you fix those tiny nitpickings above, we should be good to go! 🙌

ℹ️ _I will update this comment as you add new commits_

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by hisaac** [comment]
This PR is related to this issue #548.

File: Tests/Fixtures/Generated/Colors/swift3-context-defaults-publicAccess.swift [hunk 1]
```diff
@@ -37,7 +37,7 @@ public struct ColorName {
 // MARK: - Implementation Details
 
 // swiftlint:disable operator_usage_whitespace
-public extension Color {
+internal extension Color {
```
Comment (AliSoftware) [inline Tests/Fixtures/Generated/Colors/swift3-context-defaults-publicAccess.swift]: Shouldn't that still be `public` as this is the output of when you use the `publicAccess: true` flag?

(Note: I hope you didn't lose too much time editing the generated fixtures one by one by hand 😅  If you missed it, there's a way to automatically update all of those Generated fixtures using a dedicated Scheme, see `CONTRIBUTING.md` for more details)

Comment (hisaac) [reply Tests/Fixtures/Generated/Colors/swift3-context-defaults-publicAccess.swift]: I guess I could go either way on that, and would defer to your judgment. I changed those to internal based on @djbe's comment here: https://github.com/SwiftGen/SwiftGen/issues/548#issuecomment-427953553.

And I didn't see there was a way to generate those, but luckily it wasn't too much work to manually update them 😄

Comment (AliSoftware) [reply Tests/Fixtures/Generated/Colors/swift3-context-defaults-publicAccess.swift]: Ah, right, I missed that your PR fixed actually two things:
 - missing `public` on some lines when you use `publicAccess: true`
 - too much useless annotations on some lines (even in the public case) that shouldn't be annotated as public

TBH that comment was just a quick one after a super-quick glance at the diff, so I probably overlooked that, will take a closer look this evening :wink:

Comment (hisaac) [reply Tests/Fixtures/Generated/Colors/swift3-context-defaults-publicAccess.swift]: Whoops, that's my fault. I forgot to mention the second fix in the PR. I'll add that to the changelog and PR description.

Thanks for looking it over and let me know if there are any changes you'd like me to make 👍

File: Tests/Fixtures/Generated/Colors/swift3-context-defaults-publicAccess.swift [hunk 2]
```diff
@@ -49,7 +49,7 @@ public extension Color {
 }
 // swiftlint:enable operator_usage_whitespace
 
-public extension Color {
+internal extension Color {
```
Comment (AliSoftware) [inline Tests/Fixtures/Generated/Colors/swift3-context-defaults-publicAccess.swift]: I think this one can be kept `public` though.

In multiple places in the documentation, we say that the end user has the choice when they want to access a color using our constants, to either use `ColorName.articleBody.color` or `UIColor(named: ColorName.articleBody)`. It's up to them to use `.color` property (which is public in your example) to create the color, or to create it using `UIColor(named: )`, whichever they prefer. So I think we should still allow this one to be `public` and not force it as `internal`

Comment (AliSoftware) [reply Tests/Fixtures/Generated/Colors/swift3-context-defaults-publicAccess.swift]: Especially when you have a flat list of colors (no namespace and nested enums), you'd be able to do `UIColor(named: .articleBody)` which some people might prefer over `ColorName.articleBody.color` :wink:

File: Tests/Fixtures/Generated/Colors/swift3-context-defaults-publicAccess.swift (hunk 1 above)
Comment (hisaac) [reply Tests/Fixtures/Generated/Colors/swift3-context-defaults-publicAccess.swift]: This has been updated in 8e15873

File: Tests/Fixtures/Generated/Colors/swift3-context-defaults-publicAccess.swift (hunk 2 above)
Comment (hisaac) [reply Tests/Fixtures/Generated/Colors/swift3-context-defaults-publicAccess.swift]: Ok, that does make sense. I've made the changes in fdf42d2. 👍

**Comment by djbe** [comment]
Thx for the PR! Could you rebase this on develop so that the master commits aren't in this PR?

**Comment by hisaac** [comment]
Sure thing @djbe. Rebasing is not my forté, so hopefully I did it right. 😬

**Comment by djbe** [comment]
Jep, it's good now 👍

File: templates/colors/swift3.stencil [hunk 3]
```diff
@@ -46,7 +46,7 @@
 // MARK: - Implementation Details
 
 // swiftlint:disable operator_usage_whitespace
-{{accessModifier}} extension {{colorAlias}} {
+internal extension {{colorAlias}} {
```
[the remark this answers is not in the document]
Comment (hisaac) [reply templates/colors/swift3.stencil]: 🤔 hmm, I'm not sure. That's a good question.

Looking at the code also makes me wonder if [the typealiases at the top of the file](https://github.com/SwiftGen/SwiftGen/blob/a975280a40050489392137df49d2d5e03b363367/templates/colors/swift3.stencil#L9) should be private too.

**Comment by djbe** [comment]
Quick review of other parsers/templates:
- Fonts: looks ok, I think we can make the `FontConvertible.path` property private if we want.
- IB: scenes and segues look ok.
- JSON/Plist/YAML: looks ok.
- Strings: looks ok.
- XCAssets: looks ok.

**Comment by AliSoftware** [comment]
I think someone asked for the path of fonts to be publicly available a while ago actually (don't remember what was their use case though). Not a big deal to not make it private 😉

**Comment by AliSoftware** [comment]
Btw, anyone tried again to make those typealiases private to see if it's better handled in Swift 4?

**Comment by djbe** [comment]
Just tried it:
> Property cannot be declared public because its type uses an internal type
this is on:
```swift
public var color: Color { return Color(named: self) }
```

**Comment by AliSoftware** [comment]
All right so same error as when I tried it in early Swift days, no change in Swift 4 it seems 😢

**Comment by AliSoftware** [comment]
Thanks again @hisaac for this great contribution 👍

**Comment by hisaac** [comment]
You're welcome! Thank you both for guiding me through the process.

**Comment by hisaac** [comment]
Hey guys, any estimate on when this fix will be going out into the main branch?

**Comment by djbe** [comment]
I'm hoping I can get some time to implement the fix for #551 in Stencil this week(end), and when that's released, we should be able to release a SwiftGen version shortly thereafter.

**Comment by hisaac** [comment]
Alrighty!
